### PR TITLE
Toggle Switch Cover Improvements

### LINKED ISSUE #106: Toggle switches not interactable if cover is not completely open
**Describe the bug**
The toggle switches with a safety cover are not interactable if the cover is not *completely* open.

**To Reproduce**
1. Open the cover on any toggle switch that has one
2. The cover will  most likely not be completely open
3. Can't interact with the toggle switch

**Expected behavior**
The cover should snap open when pushed beyond a threshold, or make the switch useable if the cover is opened above some value.

**Log**
Not applicable

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - KSP Version: 1.12.3
 - VR Hardware: Valve Index
 - Kerbal-VR Version: v0.6.0

**Additional context**
Not applicable

### PR DESCRIPTION
**Pull request by Icecovery**
Changes in this PR should fix #106 and #108 

---

Original PR: 

**Add Snapping to Switch Covers**

https://user-images.githubusercontent.com/22954985/187051143-4410819b-ef2f-4085-9617-3bbc47e32fd0.mp4

### CODE REVIEW

**Comment by JonnyOThan** [comment]
Thanks for grabbing this!  Couple things:
1. Could you define the snapping threshold as a fraction of the travel distance instead of an angle? This should allow most content to work well without explicitly setting it.
2. I usually don’t submit the DLLs until it’s time for a release. Really I should probably remove them from the repo.
3. It looks like the snap will occur even when the finger is still in contact?  My first instinct would have been to only snap when the finger stops overlapping the collider, but I’d have to try it out.

**Comment by Icecovery** [comment]
I added snap-off to the covers. Snap-on and snap-off use two separate percentage thresholds for snapping. The default snapping threshold is also less aggressive now as shown in this video.

https://user-images.githubusercontent.com/22954985/187053048-3613d79e-f8c1-4f6a-9b72-963dd59bd56b.mp4

**Comment by Icecovery** [comment]
9f44d67 should fix #108

https://user-images.githubusercontent.com/22954985/187055854-b15c35a4-1b13-432f-b6e7-01cee7195168.mp4

**Comment by JonnyOThan** [comment]
merged in https://github.com/JonnyOThan/Kerbal-VR/commit/1103a57471cf5587441da0462128901970968c56

**Pull request closed without merging**
